<a href="https://colab.research.google.com/github/the-y9/Deep-Learning-using-PyTorch/blob/main/Day2_DL_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Networks
- optimiztion algorithms - torch.optim

In [1]:
import torch.optim as optim

## Optimizers

In [2]:
# optimizer = optim.SGD(model.parameters(), lr=0.1,) # model will be build, lr = momentum, nesterov = boolean, weight_decay for regularization

In [3]:
# optimizer = optim.Adagrad(p, lr = 0.01)

In [4]:
# optimizer = optim.RMSProp(p, lr = 0.01, alpha = 0.99)

In [5]:
# optimizer = optim.Adam(p,lr = 0.01)

## ANN
- nn.Linear
- nn.Module
- nn.Sequential

###  nn.Linear
Fully Connected layers

$y= Wx+b$

in-features, out-features, bias(= True by default)

In [6]:
import torch
import torch.nn as nn

In [7]:
layer1 = nn.Linear(in_features = 3, out_features= 2)
in1 = torch.tensor([1.0,2,3])
out1 = layer1(in1)
print(out1)

tensor([-1.0533,  0.4730], grad_fn=<ViewBackward0>)


In [8]:
layer1.weight

Parameter containing:
tensor([[ 0.1355, -0.0064, -0.3256],
        [ 0.0345,  0.5396, -0.3962]], requires_grad=True)

In [9]:
layer1.bias

Parameter containing:
tensor([-0.1991,  0.5479], requires_grad=True)

In [10]:
type(layer1.weight),type(layer1.bias)

(torch.nn.parameter.Parameter, torch.nn.parameter.Parameter)

In [11]:
layer1.weight.data

tensor([[ 0.1355, -0.0064, -0.3256],
        [ 0.0345,  0.5396, -0.3962]])

In [12]:
new_weight = torch.tensor([[0.5,-0.5,1],[1.5,-1.5,0]])
new_bias = torch.tensor([0.1,-0.1])

layer1.weight.data = new_weight
layer1.bias.data = new_bias

In [13]:
out1 = layer1(in1)
out1

tensor([ 2.6000, -1.6000], grad_fn=<ViewBackward0>)

In [14]:
new_weight.requires_grad

False

In [15]:
# but
layer1.weight.requires_grad

True

In [16]:
batch_input = torch.tensor([[1.0,2,3],[3.0,5,6],[7.0,8,9],[7.0,8,9]])
batch_output = layer1(batch_input)
print(batch_output)

tensor([[ 2.6000, -1.6000],
        [ 5.1000, -3.1000],
        [ 8.6000, -1.6000],
        [ 8.6000, -1.6000]], grad_fn=<AddmmBackward0>)


### nn.Module
- ```def __init__(self)```
- ```def forward()```


In [17]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super(LinearRegressionModel, self).__init__()
    self.layer1 = nn.Linear(in_features = 1, out_features = 1)

  def forward(self, x):
    return self.layer1(x)

model = LinearRegressionModel()


In [18]:
X = torch.linspace(0,10,15).reshape(-1,1)
pred = model(X)
pred

tensor([[-0.0260],
        [ 0.4987],
        [ 1.0233],
        [ 1.5479],
        [ 2.0726],
        [ 2.5972],
        [ 3.1218],
        [ 3.6465],
        [ 4.1711],
        [ 4.6957],
        [ 5.2204],
        [ 5.7450],
        [ 6.2696],
        [ 6.7942],
        [ 7.3189]], grad_fn=<AddmmBackward0>)

In [19]:
model.layer1.weight, model.layer1.bias

(Parameter containing:
 tensor([[0.7345]], requires_grad=True),
 Parameter containing:
 tensor([-0.0260], requires_grad=True))

In [20]:
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel,self).__init__()
    self.layer1 = nn.Linear(10,5)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(5,1)

  def forward(self, x):
      # sequence matters
      x = self.layer1(x)
      x = self.relu(x)
      x = self.layer2(x)
      return x

In [21]:
net = SimpleModel()
net

SimpleModel(
  (layer1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (layer2): Linear(in_features=5, out_features=1, bias=True)
)

In [22]:
input = torch.randn(1, 10)
output = net(input)
output

tensor([[0.2079]], grad_fn=<AddmmBackward0>)

In [23]:
print(net.layer1.weight,net.layer1.bias,net.layer2.weight,net.layer2.bias,sep = '\n')

Parameter containing:
tensor([[ 0.0404, -0.1469, -0.1907,  0.2462, -0.1225, -0.0082, -0.2962,  0.0434,
          0.2343,  0.2650],
        [-0.1706, -0.1443,  0.0590,  0.3043,  0.1936, -0.0537, -0.0600,  0.1998,
         -0.2567,  0.2654],
        [ 0.0217,  0.2638,  0.0696,  0.0583,  0.0917,  0.3058, -0.2155, -0.0714,
          0.0670, -0.2030],
        [-0.0737, -0.2822, -0.0912, -0.1067, -0.1922,  0.1683,  0.2746, -0.0882,
          0.2765, -0.0686],
        [ 0.1554,  0.1208, -0.1909,  0.0490,  0.2657, -0.2497,  0.0523,  0.0569,
         -0.2242,  0.2096]], requires_grad=True)
Parameter containing:
tensor([-0.2254, -0.1272, -0.2755, -0.2292, -0.2729], requires_grad=True)
Parameter containing:
tensor([[ 0.1593,  0.2306,  0.0015, -0.1022,  0.1514]], requires_grad=True)
Parameter containing:
tensor([0.1279], requires_grad=True)


In [24]:
for e in net.parameters():
  print(e)

Parameter containing:
tensor([[ 0.0404, -0.1469, -0.1907,  0.2462, -0.1225, -0.0082, -0.2962,  0.0434,
          0.2343,  0.2650],
        [-0.1706, -0.1443,  0.0590,  0.3043,  0.1936, -0.0537, -0.0600,  0.1998,
         -0.2567,  0.2654],
        [ 0.0217,  0.2638,  0.0696,  0.0583,  0.0917,  0.3058, -0.2155, -0.0714,
          0.0670, -0.2030],
        [-0.0737, -0.2822, -0.0912, -0.1067, -0.1922,  0.1683,  0.2746, -0.0882,
          0.2765, -0.0686],
        [ 0.1554,  0.1208, -0.1909,  0.0490,  0.2657, -0.2497,  0.0523,  0.0569,
         -0.2242,  0.2096]], requires_grad=True)
Parameter containing:
tensor([-0.2254, -0.1272, -0.2755, -0.2292, -0.2729], requires_grad=True)
Parameter containing:
tensor([[ 0.1593,  0.2306,  0.0015, -0.1022,  0.1514]], requires_grad=True)
Parameter containing:
tensor([0.1279], requires_grad=True)


In [25]:
for e in net.parameters():
  print(e.shape)

torch.Size([5, 10])
torch.Size([5])
torch.Size([1, 5])
torch.Size([1])


### nn.Sequential

In [26]:
# Sequence matters
model = nn.Sequential(
    nn.Linear(10,5),
    nn.ReLU(),
    nn.Linear(5,1)
    )

print(model)

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=1, bias=True)
)


In [27]:
input = torch.randn(1,10) #randn for 10 standard distribution around 1
model(input)

tensor([[-0.6841]], grad_fn=<AddmmBackward0>)

layers accessed using indices

In [28]:
model[0].weight, model[2].bias

(Parameter containing:
 tensor([[-0.1928,  0.0636,  0.1670, -0.0565,  0.3063,  0.1361, -0.2663, -0.0919,
           0.1116,  0.2846],
         [-0.2812,  0.2558,  0.2144, -0.0676,  0.1437, -0.0112, -0.2885,  0.1146,
          -0.1487, -0.0011],
         [-0.2972, -0.1650,  0.1825,  0.1136,  0.0884,  0.1065,  0.0764,  0.0604,
          -0.1824, -0.2008],
         [ 0.1093, -0.2725, -0.0992,  0.1228, -0.3006, -0.0228, -0.2733, -0.2773,
           0.0187, -0.0926],
         [-0.1135, -0.2175, -0.0165,  0.2730,  0.2345, -0.1678,  0.3027, -0.1267,
          -0.1576,  0.0154]], requires_grad=True),
 Parameter containing:
 tensor([-0.2471], requires_grad=True))

## Training
Predict $ y_pred $ compute $loss$ run optimizer update $weights$

To optimize use ```loss.backward()```
- loss
- optimizer
- Training loop

### Optimization

In [29]:
class SimpleModel(nn.Module):
  def __init__(self):
    super(SimpleModel,self).__init__()
    self.layer1 = nn.Linear(10,5)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(5,1)

  def forward(self, x):
      # sequence matters
      x = self.layer1(x)
      x = self.relu(x)
      x = self.layer2(x)
      return x

net = SimpleModel()

inputs = torch.randn(100, 10)
targets = torch.randn(100, 1)

criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr = 0.01)

for epoch in range(1000):
  optimizer.zero_grad() # 1. gradients are not accumulated now

  # 2. forward pass
  outputs = net(inputs)

  # 3. loss computation
  loss = criterion(outputs, targets)

  # 4. backpropagation
  loss.backward()

  # 5. update the parameters
  optimizer.step()

  if epoch % 100 == 0:
    print(f"Epoch: {epoch}, Loss: {loss.item()}")

Epoch: 0, Loss: 1.2149443626403809
Epoch: 100, Loss: 1.0213541984558105
Epoch: 200, Loss: 0.9979915022850037
Epoch: 300, Loss: 0.9739821553230286
Epoch: 400, Loss: 0.9482506513595581
Epoch: 500, Loss: 0.9304660558700562
Epoch: 600, Loss: 0.9093186855316162
Epoch: 700, Loss: 0.8794713020324707
Epoch: 800, Loss: 0.853132426738739
Epoch: 900, Loss: 0.8286287784576416


In [30]:
torch.save(net, 'model.pt')

## ANN Full Example

In [31]:
import numpy as np
X = np.random.rand(100, 1)*10
true_w = 3
true_b = 2
y = true_w*X + true_b + np.random.randn(100, 1)*0.2


In [32]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X,y, test_size = 0.2,random_state= 24)

In [33]:
xtraint = torch.tensor(xtrain,dtype = torch.float32)
xtestt = torch.tensor(xtest,dtype = torch.float32)
ytraint = torch.tensor(ytrain,dtype = torch.float32)
ytestt = torch.tensor(ytest,dtype = torch.float32)


In [34]:
class LinReg(nn.Module):
  def __init__(self):
    super(LinReg, self).__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x):
      return self.linear(x)

model = LinReg()

In [35]:
model.linear.weight.item()

-0.6927599906921387

In [36]:
model.linear.bias.item()

-0.8608417510986328

In [37]:
# Training group
critierion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

for epoch in range(1000):
  optimizer.zero_grad()
  outputs = model(xtraint)
  loss = critierion(outputs, ytraint)
  loss.backward()
  optimizer.step()

  if (epoch+1) %100 ==0:
    print(f"Epoch: {epoch}, Loss: {loss.item()}, Weight: {model.linear.weight.item()}, Bias:{model.linear.bias.item()} ")


Epoch: 99, Loss: 0.5111268758773804, Weight: 3.2122929096221924, Bias:0.6227613687515259 
Epoch: 199, Loss: 0.22217229008674622, Weight: 3.130216121673584, Bias:1.1468133926391602 
Epoch: 299, Loss: 0.11262612044811249, Weight: 3.0796797275543213, Bias:1.4694833755493164 
Epoch: 399, Loss: 0.07109572738409042, Weight: 3.0485634803771973, Bias:1.6681581735610962 
Epoch: 499, Loss: 0.055351197719573975, Weight: 3.029404640197754, Bias:1.7904857397079468 
Epoch: 599, Loss: 0.049382131546735764, Weight: 3.0176079273223877, Bias:1.865805983543396 
Epoch: 699, Loss: 0.04711917042732239, Weight: 3.0103445053100586, Bias:1.9121824502944946 
Epoch: 799, Loss: 0.046261269599199295, Weight: 3.0058722496032715, Bias:1.940737247467041 
Epoch: 899, Loss: 0.04593605548143387, Weight: 3.0031187534332275, Bias:1.958318829536438 
Epoch: 999, Loss: 0.04581274837255478, Weight: 3.0014233589172363, Bias:1.9691439867019653 


In [38]:
with torch.no_grad(): # does not calculate gradients when not required
  preds = model(xtestt)
  test_loss = criterion(preds, ytestt)

print(test_loss)

tensor(0.0323)


In [39]:
print(model.linear.weight.item())
print(model.linear.bias.item())

3.0014233589172363
1.9691439867019653


## Assignment - Real World data ANN using California Housing Data

In [151]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()
type(data.data),type(data.target)

(numpy.ndarray, numpy.ndarray)

In [153]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(data.data,data.target,random_state=42, test_size = 0.25)
for i in [xtrain, xtest, ytrain, ytest]:
  print(f"{i.shape}")

(15480, 8)
(5160, 8)
(15480,)
(5160,)


In [154]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.6f' % x)
pd.DataFrame(xtrain).describe()

0            1            2            3            4  \
count 15480.000000 15480.000000 15480.000000 15480.000000 15480.000000   
mean      3.878314    28.595995     5.435598     1.096881  1427.497287   
std       1.903788    12.611330     2.421650     0.438804  1142.930862   
min       0.499900     1.000000     0.888889     0.333333     3.000000   
25%       2.566925    18.000000     4.450000     1.006593   788.750000   
50%       3.543900    29.000000     5.232331     1.049346  1167.000000   
75%       4.762500    37.000000     6.058141     1.100143  1727.000000   
max      15.000100    52.000000   141.909091    25.636364 35682.000000   

                 5            6            7  
count 15480.000000 15480.000000 15480.000000  
mean      3.106660    35.646720  -119.583736  
std      11.955834     2.133950     2.002442  
min       0.692308    32.550000  -124.350000  
25%       2.430205    33.940000  -121.800000  
50%       2.817672    34.270000  -118.510000  
75%       3.280020    37.720000  -118.010000  
max    1243.333333    41.950000  -114.310000

In [158]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
# ssx = StandardScaler()
ssx = MinMaxScaler()
xtrains = ssx.fit_transform(xtrain)
pd.DataFrame(xtrains).describe()

0            1            2            3            4  \
count 15480.000000 15480.000000 15480.000000 15480.000000 15480.000000   
mean      0.232991     0.541098     0.032242     0.030176     0.039925   
std       0.131294     0.247281     0.017172     0.017342     0.032034   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.142551     0.333333     0.025252     0.026608     0.022023   
50%       0.209928     0.549020     0.030800     0.028298     0.032624   
75%       0.293968     0.705882     0.036656     0.030305     0.048320   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

                 5            6            7  
count 15480.000000 15480.000000 15480.000000  
mean      0.001943     0.329438     0.474728  
std       0.009621     0.227016     0.199446  
min       0.000000     0.000000     0.000000  
25%       0.001399     0.147872     0.253984  
50%       0.001710     0.182979     0.581673  
75%       0.002082     0.550000     0.631474  
max       1.000000     1.000000     1.000000

In [159]:
# ssy = StandardScaler()
ssy = MinMaxScaler()
ytrains = ssy.fit_transform(ytrain.reshape(-1,1))
pd.DataFrame(ytrains).describe()

0
count 15480.000000
mean      0.395949
std       0.238177
min       0.000000
25%       0.215826
50%       0.339382
75%       0.514845
max       1.000000

In [160]:
np.set_printoptions(precision=6, suppress=True)

In [161]:
xtraint = torch.tensor(xtrains,dtype = torch.float32)
ytraint = torch.tensor(ytrains, dtype = torch.float32)
type(xtraint),type(ytraint)

(torch.Tensor, torch.Tensor)

In [194]:
class Linear(nn.Module):
  def __init__(self):
    super(Linear, self).__init__()
    self.linear = nn.Linear(8,1)

  def forward(self, x):
    return self.linear(x)
lm = Linear()

In [195]:
# Training
criteria = nn.MSELoss()
optimiser = optim.SGD(lm.parameters(), lr= 0.001,momentum = 0.9,nesterov=True)

for epoch in range(1000):
  optimiser.zero_grad()
  outputs = lm(xtraint)
  loss = criteria(outputs, ytraint)
  loss.backward()
  optimiser.step()

  if epoch<10:
    print(f"Epoch: {epoch}, Loss: {loss.item()}, Weight: {lm.linear.weight.data}, Bias:{lm.linear.bias.item()} ")
  elif epoch<100 and (epoch+1) % 10 == 0:
    print(f"Epoch: {epoch}, Loss: {loss.item()}, Weight: {lm.linear.weight.data}, Bias:{lm.linear.bias.item()} ")
  elif (epoch+1) % 100 ==0 :
    print(f"Epoch: {epoch}, Loss: {loss.item()}, Weight: {lm.linear.weight.data}, Bias:{lm.linear.bias.item()} ")

Epoch: 0, Loss: 0.15754817426204681, Weight: tensor([[ 0.0055,  0.1059, -0.1277,  0.0948, -0.0759,  0.0340,  0.2966, -0.1593]]), Bias:0.025007478892803192 
Epoch: 1, Loss: 0.1564016193151474, Weight: tensor([[ 0.0060,  0.1067, -0.1276,  0.0949, -0.0759,  0.0340,  0.2969, -0.1585]]), Bias:0.02660677209496498 
Epoch: 2, Loss: 0.1547861397266388, Weight: tensor([[ 0.0066,  0.1078, -0.1275,  0.0949, -0.0758,  0.0340,  0.2974, -0.1574]]), Bias:0.028624845668673515 
Epoch: 3, Loss: 0.1527685970067978, Weight: tensor([[ 0.0074,  0.1091, -0.1275,  0.0950, -0.0757,  0.0340,  0.2979, -0.1561]]), Bias:0.031011708080768585 
Epoch: 4, Loss: 0.15041257441043854, Weight: tensor([[ 0.0082,  0.1106, -0.1274,  0.0951, -0.0756,  0.0341,  0.2986, -0.1547]]), Bias:0.03372126817703247 
Epoch: 5, Loss: 0.14777766168117523, Weight: tensor([[ 0.0092,  0.1122, -0.1273,  0.0952, -0.0754,  0.0341,  0.2992, -0.1531]]), Bias:0.03671109303832054 
Epoch: 6, Loss: 0.14491912722587585, Weight: tensor([[ 0.0102,  0.1139

In [196]:
xtests = ssx.transform(xtest)
ytests = ssy.transform(ytest.reshape(-1,1))
xtestt = torch.tensor(xtests, dtype=torch.float32)
ytestt = torch.tensor(ytests, dtype = torch.float32)

In [197]:
with torch.no_grad():
  ypred = lm(xtestt)
  mseloss = criteria(ypred, ytestt)
print(f"MSE loss: {mseloss}")

MSE loss: 0.041391804814338684


In [198]:
criteria(ypred, ytestt)
print(f"MSE loss: {criteria(ypred, ytestt)}")

criterion = nn.L1Loss()
print(f"L1 loss: {criterion(ypred, ytestt)}")

criterion = torch.nn.SmoothL1Loss()
print(f"Smooth L1 loss: {criterion(ypred, ytestt)}")

MSE loss: 0.041391804814338684
L1 loss: 0.16029399633407593
Smooth L1 loss: 0.020695902407169342
