<a href="https://colab.research.google.com/github/the-y9/Deep-Learning-using-PyTorch/blob/main/Day1_DL_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.4.0+cu121'

In [ ]:
l = [1,2,3]
t1 = torch.tensor(l)
t1

tensor([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
npa = np.array(l)
t2 = torch.tensor(npa)
t2

tensor([1, 2, 3])

In [ ]:
t1 = torch.ones((2,2))
t1

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
t3 = torch.rand((2,2))
t3

tensor([[0.2421, 0.2736],
        [0.4654, 0.4064]])

In [ ]:
t4 = torch.randint(0,10,size = (2,2))
t4

tensor([[3, 5],
        [8, 5]])

In [ ]:
t5 = torch.arange(0,10,3)
t5

tensor([0, 3, 6, 9])

In [ ]:
t5 = torch.arange(0,9).reshape(3,3)
t5

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
t10 = torch.zeros_like(t5)
t10

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
t10 = torch.ones_like(t5)
t5


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Tensor attributes

### ndim, shape

In [ ]:

t1 = torch.tensor(4)
t2 = torch.tensor([1,2,3])
t3 = torch.tensor([[1,2,3],[1,2,3]])
t4 = torch.tensor([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

print(t1.ndim,t2.ndim,t3.ndim,t4.ndim)
print(t1.shape,t2.shape,t3.shape,t4.shape)

0 1 2 3
torch.Size([]) torch.Size([3]) torch.Size([2, 3]) torch.Size([2, 2, 3])


### dtpye
- torch.float32 (float)
- torch.float64 (double)
- torch.int32 (int)
- torch.int64 (long)
- torch.int8 - 8bits

In [ ]:
t1 = torch.tensor([1,2,3], dtype = torch.int8)
print(t1.dtype,t1)

torch.int8 tensor([1, 2, 3], dtype=torch.int8)


In [ ]:
t2 = torch.tensor([1.0,2,3], requires_grad = True)
t2

tensor([1., 2., 3.], requires_grad=True)

### t.device


In [ ]:
t1.device

device(type='cpu')

In [ ]:
torch.cuda.is_available()

True

In [ ]:
cuda_tensor = torch.tensor([1.0,2,3],device = 'cuda')
cuda_tensor.device

device(type='cuda', index=0)

In [ ]:
cuda_tensor = cuda_tensor.to('cpu')
cuda_tensor.device

device(type='cpu')

In [ ]:
t1 = t1.to('cuda')
t1.device

device(type='cuda', index=0)

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

## accessing elements

In [ ]:
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t[0]

tensor([1, 2, 3])

In [ ]:
t[0][0]

tensor(1)

In [ ]:
t[:2]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t[:,-1]

tensor([3, 6, 9])

In [ ]:
t[1,1:]

tensor([5, 6])

## broadcast

In [ ]:
t = torch.tensor([[[1,2,3,4,5,6],[1,2,6,4,8,23]]])
t>3

tensor([[[False, False, False,  True,  True,  True],
         [False, False,  True,  True,  True,  True]]])

## standard function
- torch.sum()
- max
- min
- torch.mul() - a*b
- matmul() a@b
- .T Transpose
- save(a,'filename')
- load('filename')

In [ ]:
t1 = torch.tensor([1,2,3])
t1 + 10 #also broadcast

tensor([11, 12, 13])

In [ ]:
t1.sum() # or torch.sum(t1)

tensor(6)

In [ ]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
torch.sum(t1,dim = 0)

tensor([5, 7, 9])

In [ ]:
torch.max(t1, dim = 1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
a*b # or torch.mul(a,b)

tensor([ 4, 10, 18])

In [ ]:
a=  torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,2],[3,4]])
a@b # or torch.matmul(a,b)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
b.T

tensor([[1, 3],
        [2, 4]])

In [ ]:
torch.save(a,'tensor_a.pt')

In [ ]:
t2 = torch.load('tensor_a.pt')
t2 = torch.tensor([[1.0,2],[3,4]])

<ipython-input-63-93d77877e8f7>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  t2 = torch.load('tensor_a.pt')


In [ ]:
t1 = torch.tensor([[1.00001, 2.00001],[3.00001,4.00001]])
torch.allclose(t1,t2, atol = 1e-4)

True

In [ ]:
torch.linspace(-5,5,10)

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])

In [ ]:
t2 = t # different names shallow copy
t2 = torch.clone(t1)
t1,t2

(tensor([[1.0000, 2.0000],
         [3.0000, 4.0000]]),
 tensor([[1.0000, 2.0000],
         [3.0000, 4.0000]]))

## autograd

In [ ]:
x = torch.tensor(2.0, requires_grad = True)
y = torch.tensor(3.0, requires_grad = False)
z = 3*x**2 + 4*y**2
z.backward()
x.grad, y.grad

(tensor(12.), None)

In [ ]:
x = torch.tensor(2.0, requires_grad = False)
w = torch.tensor(3.0, requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)

y = w * x + b # computed tensor

y.backward()
x.grad, w.grad, b.grad

(None, tensor(2.), tensor(1.))

In [ ]:
x.requires_grad

False

## leaf tensors
We create them not using operations but using ```torch.tensor()``` or ```torch.rand()```.

Gradients is only computed for leaf nodes and that too only for those where ```requires_grad = True```.
- is_leaf

In [ ]:
x = torch.ones(2,2, requires_grad = True) #leaf
y = x+2 #intermediate
z = y*y*3
out = z.mean()

out.backward()
x.grad, y.grad, z.grad

<ipython-input-89-372c3727bbe9>:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  x.grad, y.grad, z.grad


(tensor([[4.5000, 4.5000],
         [4.5000, 4.5000]]),
 None,
 None)

In [ ]:
a = torch.rand(2,2) #requires_grad != True
b = a+2
a.is_leaf,b.is_leaf # so both True

(True, True)

In [ ]:
c = torch.rand(2,2, requires_grad = True) #requires_grad = True
d = c+2
c.is_leaf,d.is_leaf # so c True d False

(True, False)

In [ ]:
x = torch.ones(2,2, requires_grad = True) #leaf
y = x+2 #intermediate
z = y*y*3
out = z.mean()

y.retain_grad()
z.retain_grad()
out.backward()
print(x.is_leaf, y.is_leaf, z.is_leaf) # leaf status reamins same
print(x.grad, y.grad, z.grad,sep='\n')

True False False
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


## activation functions
  - torch.relu()
  - torch.sigmoid()
  - torch.tanh()
  - torch.nn
    - torch.nn.ReLU
    - torch.nn.Sigmoid
    - torch.nn.Tanh
    - torch.nn.Softmax
    - torch.nn.LeakyReLU
    - torch.nn.ELU
    - torch.nn.functional
      - torch.nn.functional.relu()
      - torch.nn.functional.sigmoid()
      -.
      -.
      -.


In [ ]:
import torch.nn as nn

In [ ]:
x = torch.tensor([-2.0,1,0,1,2])
print(torch.relu(x))

tensor([0., 1., 0., 1., 2.])


In [ ]:
obj = nn.ReLU()
obj(x)

tensor([0., 1., 0., 1., 2.])

In [ ]:
nn.functional.relu(x)

tensor([0., 1., 0., 1., 2.])

## Loss functions
- nn.MSELoss()
- nn.CrossEntropyLoss()
- nn.BCELoss()
- ... and more ...

In [ ]:
y_pred = torch.tensor([1.0,2,3,4])
y_true = torch.tensor([1.0,2,2,4])

mse = nn.MSELoss()
loss = mse(y_pred, y_true)
loss

tensor(0.2500)