<a href="https://colab.research.google.com/github/the-y9/Deep-Learning-using-PyTorch/blob/main/Day4_DL_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN
The movie was fantastic
- **seq lenghth** = 4
- **input/embedded dimension** = 5(state vector dimensions)
- **hidden dimension**
- **Linear layer** for final output
$ h_0 ->h_1->h_2->h_3->h_4 $
$  $

In [ ]:
# !pip install torch==2.0.1 torchtext==0.15.2 portalocker==2.8.2

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [ ]:
X = torch.randint(1,10,(3,10,5), dtype = torch.float32)
y = torch.tensor([1,0,1], dtype = torch.long)

In [ ]:
X,y

(tensor([[[2., 1., 7., 6., 6.],
          [4., 1., 2., 8., 5.],
          [4., 2., 1., 2., 4.],
          [9., 6., 1., 7., 4.],
          [1., 5., 8., 8., 5.],
          [8., 9., 6., 2., 8.],
          [9., 9., 8., 2., 4.],
          [2., 7., 7., 3., 4.],
          [4., 6., 7., 7., 6.],
          [7., 8., 1., 9., 2.]],
 
         [[5., 7., 4., 4., 9.],
          [2., 6., 3., 7., 8.],
          [6., 1., 9., 6., 1.],
          [1., 6., 9., 3., 1.],
          [8., 4., 6., 1., 5.],
          [2., 8., 3., 5., 8.],
          [7., 9., 1., 9., 7.],
          [5., 3., 8., 9., 2.],
          [3., 5., 3., 1., 7.],
          [8., 9., 9., 5., 5.]],
 
         [[9., 5., 8., 8., 1.],
          [3., 4., 4., 8., 6.],
          [4., 3., 2., 3., 4.],
          [6., 5., 9., 5., 9.],
          [8., 2., 5., 3., 3.],
          [4., 5., 8., 7., 5.],
          [3., 1., 9., 3., 8.],
          [6., 6., 9., 3., 8.],
          [1., 9., 6., 4., 3.],
          [5., 3., 1., 7., 9.]]]),
 tensor([1, 0, 1]))

In [ ]:
# rnn = nn.RNN(embedded, ,hidden state, no.of layers)
rnn = nn.RNN(5,3,2, batch_first = True) # (No. of examples, sequenceLength, input dimension) otherwise (L,N,I)
output, hidden = rnn(X)

In [ ]:
print(f'Output: {output},\n\n Hidden: {hidden}')

Output: tensor([[[ 0.5045,  0.1786, -0.3201],
         [ 0.6515, -0.0851, -0.1810],
         [ 0.3787,  0.0769, -0.0376],
         [ 0.5521,  0.1084, -0.3000],
         [ 0.6386, -0.0420, -0.1752],
         [ 0.0139,  0.1371,  0.0902],
         [-0.4383,  0.0641,  0.1699],
         [ 0.4530,  0.3072, -0.4711],
         [ 0.7055, -0.1989, -0.1527],
         [ 0.5455,  0.1551, -0.1572]],

        [[ 0.5159,  0.2215, -0.3548],
         [ 0.6718, -0.1121, -0.1845],
         [-0.1013, -0.5878,  0.6376],
         [-0.1682,  0.5773, -0.2876],
         [-0.3484, -0.4141,  0.3912],
         [ 0.2966,  0.5705, -0.4817],
         [ 0.7447, -0.3021, -0.2311],
         [ 0.2062, -0.2974,  0.4160],
         [ 0.0675,  0.5013, -0.3468],
         [ 0.5905, -0.2177, -0.1901]],

        [[-0.0704, -0.4534,  0.4229],
         [ 0.2828,  0.5673, -0.4557],
         [ 0.6799, -0.3067, -0.1731],
         [ 0.5087,  0.1982, -0.1122],
         [-0.5247, -0.5452,  0.6538],
         [ 0.1437,  0.6843, -0.5575],


In [ ]:
rnn.weight_hh_l1 # hidden to hidden layer 1; ih input to hidden

Parameter containing:
tensor([[ 0.0329,  0.3023, -0.3848],
        [-0.1351, -0.4958,  0.4408],
        [ 0.1412, -0.2268, -0.4836]], requires_grad=True)

## Define Model

In [ ]:
class simplernn(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super(simplernn, self).__init__()
    self.rnn = nn.RNN(input_size, hidden_size, batch_first = True)
    self.fc = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    out, hidd = self.rnn(x)
    final_hidden_state = hidd[-1]
    return self.fc(final_hidden_state)

In [ ]:
inp = 5
hid = 3
out = 2

model = simplernn(inp, hid, out)

## Training

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.01)

In [ ]:
#zerograd,forward,loss,backward,update
for epoch in range(3):
  running_loss = 0
  model.train()
  output = model(X)
  loss = criterion(output, y)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  running_loss += loss.item()
  print(f"Running Loss: {running_loss} for Epoch: {epoch}")

Running Loss: 0.8875702023506165 for Epoch: 0
Running Loss: 0.8181796669960022 for Epoch: 1
Running Loss: 0.7569066882133484 for Epoch: 2


In [ ]:
# !pip install torchtext==0.15.2

In [ ]:
import torchtext
import torchtext.datasets as datasets
dir(datasets)

['AG_NEWS',
 'AmazonReviewFull',
 'AmazonReviewPolarity',
 'CC100',
 'CNNDM',
 'CoLA',
 'CoNLL2000Chunking',
 'DATASETS',
 'DBpedia',
 'EnWik9',
 'IMDB',
 'IWSLT2016',
 'IWSLT2017',
 'MD5',
 'MNLI',
 'MRPC',
 'Multi30k',
 'NUM_LINES',
 'PennTreebank',
 'QNLI',
 'QQP',
 'RTE',
 'SQuAD1',
 'SQuAD2',
 'SST2',
 'STSB',
 'SogouNews',
 'UDPOS',
 'URLS',
 'WNLI',
 'WikiText103',
 'WikiText2',
 'YahooAnswers',
 'YelpReviewFull',
 'YelpReviewPolarity',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'ag_news',
 'amazonreviewfull',
 'amazonreviewpolarity',
 'cc100',
 'cnndm',
 'cola',
 'conll2000chunking',
 'dataset',
 'dataset_module',
 'dataset_module_path',
 'dbpedia',
 'enwik9',
 'imdb',
 'importlib',
 'iwslt2016',
 'iwslt2017',
 'mnli',
 'mrpc',
 'multi30k',
 'penntreebank',
 'qnli',
 'qqp',
 'rte',
 'sogounews',
 'squad1',
 'squad2',
 'sst2',
 'stsb',
 'udpos',
 'wikitext103',
 'wikitext2',
 'wnli',

In [ ]:
train_iter = datasets.IMDB(split='train')

In [ ]:
# for label, sent in train_iter:
#   print(sent)
#   break

AttributeError: 'NoneType' object has no attribute 'Lock'
This exception is thrown by __iter__ of _MemoryCellIterDataPipe(remember_elements=1000, source_datapipe=_ChildDataPipe)

## Preprocessing
- Tokenization
- Creating Vocabualry
  - numericalization
- Word Embedding

In [ ]:
from torchtext.data.utils import get_tokenizer

In [ ]:
tokenizer = get_tokenizer('basic_english') # spacy, nltk

In [ ]:
string = 'Hello! This is the 4th day of DL workshop.'
tokenizer(string)

['hello', '!', 'this', 'is', 'the', '4th', 'day', 'of', 'dl', 'workshop', '.']

## Tokenizer

In [ ]:
def yield_tokens(train_iter):
  for lab, text in train_iter:
    yield tokenizer(text)

In [ ]:
from torchtext.vocab import build_vocab_from_iterator

In [ ]:
vocab = build_vocab_from_iterator(yield_tokens(train_iter), min_freq = 20, max_tokens = 20000, specials=['<unk>','<pad>'])
vocab.set_default_index(vocab['<unk>'])

AttributeError: 'NoneType' object has no attribute 'Lock'
This exception is thrown by __iter__ of _MemoryCellIterDataPipe(remember_elements=1000, source_datapipe=_ChildDataPipe)

In [ ]:
vocab['i'], len(vocab)

In [ ]:
vocab.get_stoi()

In [ ]:
vocab.get_itos()

In [ ]:
tokenizer(string)

In [ ]:
vocab(tokenizer(string))

## Padding

In [ ]:
from torch.nn.utils.rnn import pad_sequence

In [ ]:
sentences = [torch.tensor([1,2,3,4]), torch.tensor([4,5]), torch.tensor([1,7,6])]

In [ ]:
pad_sequence(sentences, batch_first = True, padding_value=1) # default padding_value=0

## From Scratch

Unzipping the format in

(label,sentence)

To

(labels,...) (sentences,...)

In [ ]:
bt = [(1,'2'),(4,'5')]
lab, text = zip(*bt)
lab,text

In [ ]:
def text_to_tensor(text):
  tokens = tokenizer(text)
  return torch.tensor(vocab(tokens))

In [ ]:
def collate_fn(batch):
  labels, texts = zip(*batch)
  texts = [text_to_tensor(text) for text in texts]
  texts = pad_sequence(texts, batch_first = True, padding_value = vocab['<pad>'])
  labels = torch.tensor([label for label in labels])
  return labels, texts

In [ ]:
from torch.utils.data import DataLoader
train_iter = datasets.IMDB(split = 'train')

In [ ]:
train_loader = DataLoader(train_iter,batch_size = 32, collate_fn = collate_fn)

In [ ]:
train_loader

TypeError: 'DataLoader' object is not subscriptable

In [ ]:
for targets, sents in train_loader:
  print(sents.shape)
  break

/usr/local/lib/python3.10/dist-packages/torch/utils/data/datapipes/iter/combining.py:297: UserWarning: Some child DataPipes are not exhausted when __iter__ is called. We are resetting the buffer and each child DataPipe will read from the start again.
  warnings.warn("Some child DataPipes are not exhausted when __iter__ is called. We are resetting "


AttributeError: 'NoneType' object has no attribute 'Lock'
This exception is thrown by __iter__ of _MemoryCellIterDataPipe(remember_elements=1000, source_datapipe=_ChildDataPipe)

In [ ]:
class Rnn(nn.Module):
  def __init__(self, vocab_size, embedding_dim,hid_dim, output_dim):
    super(Rnn, self).__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.rnn = nn.RNN(embedding_dim, hid_dim, batch_first = True)
    self.fc = nn.Linear(hid_dim, output_dim)

  def forward(self, x):
    embedded = self.embedding(x)
    output, hidden = self.rnn(x)
    hidden = hidden[-1]
    return self.fc()

In [ ]:
iterator = iter(train_loader)

In [ ]:
y, feature = next(iterator)

/usr/local/lib/python3.10/dist-packages/torch/utils/data/datapipes/iter/combining.py:297: UserWarning: Some child DataPipes are not exhausted when __iter__ is called. We are resetting the buffer and each child DataPipe will read from the start again.
  warnings.warn("Some child DataPipes are not exhausted when __iter__ is called. We are resetting "


AttributeError: 'NoneType' object has no attribute 'Lock'
This exception is thrown by __iter__ of _MemoryCellIterDataPipe(remember_elements=1000, source_datapipe=_ChildDataPipe)

In [ ]:
ed = 100
vs = len(vocab)
od = 1
hd = 50

NameError: name 'vocab' is not defined

In [ ]:
rnn_model = Rnn(vs,ed,hd,od)

NameError: name 'vs' is not defined

In [ ]:
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(rnn_model.parameters(), lr = 0.1)

NameError: name 'rnn_model' is not defined

In [ ]:
rnn_model.Train()
for epoch in range(3):
  for data in train_loader:
    labels, texts = rnn_model(texts)
    loss = criterion(output.squeeze(1), labels.float())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f"Running Loss: {loss.item()} for Epoch: {epoch}")